### ISSUE TITLE
clickhousetracesexporter fails to write data

### ISSUE THREAD

**Issue by srikanthccv** [SigNoz/signoz-otel-collector#72]
The user faced an issue with getting traces ingested while there was no issue from the metrics/logs exporter.

```
github.com/SigNoz/signoz-otel-collector/exporter/clickhousetracesexporter.(*SpanWriter).writeBatch
	/src/exporter/clickhousetracesexporter/writer.go:129
github.com/SigNoz/signoz-otel-collector/exporter/clickhousetracesexporter.(*SpanWriter).backgroundWriter
	/src/exporter/clickhousetracesexporter/writer.go:108
2022-12-30T16:54:32.516Z	error	clickhousetracesexporter/writer.go:109	Could not write a batch of spans	{"kind": "exporter", "data_type": "traces", "name": "clickhousetraces", "error": "dial tcp 172.27.0.2:9000: connect: connection refused"}
github.com/SigNoz/signoz-otel-collector/exporter/clickhousetracesexporter.(*SpanWriter).backgroundWriter
```

Slack thread: https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1672250812161599

**Comment by makeavish** [comment]
It is strange that clickhouse connection only fails in clickhousetracesexporter.
Maybe it's due to high memory consumption on clickhouse server and since trace exporter writes much more data than metrics exporter so it is disconnected first.

**Comment by makeavish** [comment]
@srikanthccv We haven't updated [clickhouse-go client](https://github.com/ClickHouse/clickhouse-go/releases) too.
v2.4.2 has been released but we are still on v2.0.12.

**Comment by srikanthccv** [comment]
This was definitely an unusual issue. I wouldn't expect the connection refused but rather timed out error if the write volume can't be fulfilled. My initial suspicion was the connection handling mechanism and its settings in the traces exporter. We are on the same major version so I don't think that makes any difference. FWIW they were also using the logs but didn't see any issues with that either.

**Comment by srikanthccv** [comment]
Should be fixed now

**Comment by PiotrKula-ECO** [comment]
I am trying to evaluate SigNoz first time trying it. And in the hotel collector, I still see
`clickhousetracesexporter/writer.go:369  Could not prepare batch for model table:` 

also the schema migrotor just wont run.. i have no idea what Is going on.

**Comment by GitGreenHand** [comment]
@srikanthccv  Could you please tell me how this issue was resolved in the end?

**Comment by srikanthccv** [comment]
@GitGreenHand it was solved by fixing a bug in clickhouse-go client library.

**Comment by GitGreenHand** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by GitGreenHand** [comment]
@srikanthccv  Thank you very much. I hope you can let me know the specific version that fixes this issue. Currently, I am using github.com/ClickHouse/clickhouse-go/v2 version v2.15.0, but I'm still encountering this problem.
